# Generated by Django 5.1 on 2024-08-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_message_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=50,
            ),
        ),
    ]
