# Generated by Django 5.1 on 2024-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
